function [mel] = logMel(filepath)

[audioIn, fs] = audioread(filepath); 
mel = melSpectrogram(audioIn,fs, ...
                   'Window',hann(2048,'periodic'), ...
                   'OverlapLength',1024, ...
                   'FFTLength',4096, ...
                   'NumBands',40);
mel = transpose(mel);
end